### ISSUE TITLE
Use a RNG independent of machine, OS, endianness, etc

### ISSUE THREAD

**Issue by whitequark** [azonenberg/openfpga#15]
Instead of libc rand().

**Comment by cliffordwolf** [comment]
There's a "replace with something a bit more random!" TODO comment at https://github.com/azonenberg/openfpga/commit/69bbfee5166b9b68955917a297fba9ad337bcbe6#diff-b579c079e629248e4673f0d09231a2f2R46.

May I suggest [xorshift, xorshift*, or xorshift+](https://en.wikipedia.org/wiki/Xorshift)? Comparable (xorshift) or better (xorshift*, xorshift+) randomness than Mersenne Twister, but simpler coder and much faster.

**Comment by cliffordwolf** [comment]
^^ Ignore this. I've just seen Robert did already replace it with PCG.
