### ISSUE TITLE
build system: Make "distclean" target work

### ISSUE THREAD

**Issue by ArcaneNibble** [azonenberg/openfpga#74]
Somehow make distclean or whatever work so that switching between native and mingw isn't a huge pain. Otherwise I have to go and hunt down all of the cmake generated crap manually and remove them.

**Comment by whitequark** [comment]
Just don't do in-tree builds. (use `cd build && cmake .. && make`). You can easily have as many simultaneous build trees as you want.

**Comment by whitequark** [comment]
(also, `git clean` is the command you should use instead of doing that manually anyway.)
