### ISSUE TITLE
Support for Yosys' -q/-l/-L options

### ISSUE THREAD

**Issue by whitequark** [azonenberg/openfpga#8]
I.e. to make it possible to write everything to the log, and nothing except warnings/errors to the console. This is quite convenient to reduce the amount of noise, especially with editor buildsystem integration.

Also would be great if you flushed stdout before writing to stderr, since right now the errors are placed before the starting banner when running gp4par through Sublime Text's buildsystem integration (I think it uses pipes?)

**Comment by azonenberg** [comment]
Fixed in pull request #12
